name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]


jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.6", "3.7", "3.8", "3.9", "3.10" ]
        os: [ ubuntu-18.04, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -U pytest
      - name: Lint with flake8
        run: |
          flake8 avro_validator
      - name: Test with pytest
        run: |
          echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV
          export PYTHONPATH=${GITHUB_WORKSPACE}
          coverage run --source=avro_validator -m pytest avro_validator/tests/
      - name: ls
        run: ls -lahtr
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: coveralls --service=github
